theme: jekyll-theme-minimal
title: ðŸ‘¾ðŸ‘¾ðŸ‘¾
description: Cloud of competences 
markdown: CommonMarkGhPages 
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
logo: /tags.png
google_analytics: 
